### ISSUE TITLE
Tossed building has a chance to becoming a ghost building.

### ISSUE THREAD

**Issue by HotoCocoaco** [DosMike/TF2-TossBuildings#1]
https://youtu.be/z2HM-nwhLNs
You can see there are some fake ghost building in the video. No related errors. It's no saying that if it's harmless. But there's a chance that server can break 2048 entities limit. And it confuse ppl too.

**Comment by DosMike** [comment]
weird, it sometimes doesn't seem to do the ground check anymore...

**Comment by HotoCocoaco** [comment]
btw I use it in arena map so I edit the source to remove the check for waiting players. I don't think that's the key issue.

**Comment by DosMike** [comment]
that should be fine, yea. that is just in place to prevent escaping the spawn room early, but with buildings destructing in the spawn room it's not critical.

**Comment by HotoCocoaco** [comment]
Is there any debug scripts for me to test with?

**Comment by DosMike** [comment]
not really, i'm adding and removing debug code as i need it.

**Comment by HotoCocoaco** [comment]
map is vsh_minegay_reworked_v2

**Comment by HotoCocoaco** [comment]
turn out that if you use melee to hit `prop_physics_multiplayer` out of the ground and land to a successful pos, the sentry just teleport to it.
https://youtu.be/2ewG0x-EYIE

**Comment by DosMike** [comment]
I think this was caused by the origin not being centered in the bounding box. I'm now using the center point instead. Let me know if this fixed the issue

**Comment by HotoCocoaco** [comment]
The landing check is more stable now. But when I toss a lv2 sentry the model would be a lv1 sentry after constructing. The animation is not working normally.
Dispenser has similar bug of lv2/3. After constructing the model is good expect the construction animation is broken.
https://youtu.be/h_28iAa6rA8

It would be more stable if the tossed entity is staying vertical all the time. Or you will see this invalid entity not being destroyed.
![image](https://user-images.githubusercontent.com/42245579/173237022-f05614a1-f941-4bf1-9167-a1eaf991d558.png)

**Comment by DosMike** [comment]
The rotation of the physics prop is not really impacting the building, that will always be kept up-right. Poked at it a bit more, adjusting the model / building level. It felt pretty stable now.

**Comment by HotoCocoaco** [comment]
Tested. It's more stable and the model is basically correct now. Good work. 👍
