### ISSUE TITLE
Player is able to pile building above another building.

### ISSUE THREAD

**Issue by HotoCocoaco** [DosMike/TF2-TossBuildings#2]
![696246c58da80ada.jpg](https://user-images.githubusercontent.com/42245579/186419276-de2fb5b3-7093-4918-bbc8-88b9a6e67336.jpg)
By throwing building it can reach the sky, yeeehhhhaaaa.

**Comment by DosMike** [comment]
Version 22w44a and newer should disable throwing on top of other buildings by default. Can you please verify? :)
